<?php

declare(strict_types=1);

use CjwNetwork\RequestShield\Challenge\ChallengePage;

/** Shared by the tests (the runner and the generic helpers are in testkit/). */

/** Runs the page's script in Node on $challenge; returns [payload, took ms, hashes/s]. */
function solveInNode(array $challenge): array
{
    $node = nodeBinary();
    $file = sys_get_temp_dir() . '/rshield-js-' . getmypid() . '-' . mt_rand() . '.js';
    // Node before 16 has no btoa; browsers always do.
    $js = "if (typeof btoa === 'undefined') { global.btoa = function (s) { return Buffer.from(s, 'binary').toString('base64'); }; }\n"
        . 'var RS = ' . json_encode(['c' => $challenge]) . ";\n" . ChallengePage::SCRIPT . "\n"
        . "var t = Date.now(); RS.solve(RS.c, function (n, took) { var ms = Date.now() - t; console.log(JSON.stringify({ payload: n < 0 ? null : RS.payload(RS.c, n, took), ms: ms, n: n })); });\n";
    file_put_contents($file, $js);
    $out = shell_exec(escapeshellarg($node) . ' ' . escapeshellarg($file) . ' 2>&1');
    unlink($file);
    $r = json_decode(trim((string) $out), true);
    if (!is_array($r)) {
        throw new TestFailure('node: ' . trim((string) $out));
    }
    return [$r['payload'], (int) $r['ms'], (int) $r['n']];
}

/**
 * PHP for a server a test starts (php -S): the binary, and -- with
 * TESTS_HOSTING=minimal (the CI leg "minimal hosting", ADR 0013) -- the
 * restrictions of a tight shared host: no APCu, no allow_url_fopen, the shell
 * functions disabled, 64 MB. The shield must decide the same under them.
 */
function serverPhp(): string
{
    $php = escapeshellarg(PHP_BINARY);
    if (getenv('TESTS_HOSTING') === 'minimal') {
        $php .= ' -d apc.enabled=0 -d allow_url_fopen=0 -d memory_limit=64M'
            . ' -d disable_functions=exec,shell_exec,proc_open,popen,system,passthru,putenv,set_time_limit,dl';
    }
    return $php;
}

/**
 * The built single file the suite runs against (REQUEST_SHIELD_ENTRY, 0031
 * E.3), or null: the source tree (bootstrap.php, bin/request-shield).
 */
function rsSingle(): ?string
{
    $entry = getenv('REQUEST_SHIELD_ENTRY');
    return is_string($entry) && $entry !== '' ? $entry : null;
}

/**
 * What a test requires or prepends to have the library: bootstrap.php, or
 * with REQUEST_SHIELD_ENTRY a file next to the built one that loads it and
 * the statistics file beside it (request-shield-stats.php), then protects as
 * the built file's own bootstrap does -- the single file cannot switch the
 * statistics on by itself yet (0031 E.2, open), and most of the suite uses
 * them.
 */
function rsEntry(): string
{
    $single = rsSingle();
    return $single === null ? dirname(__DIR__) . '/bootstrap.php' : rsWrapper($single, 'entry');
}

/** The command line: bin/request-shield, or Cli::main() from the built file (and the statistics file). */
function rsCli(): string
{
    $single = rsSingle();
    return $single === null ? dirname(__DIR__) . '/bin/request-shield' : rsWrapper($single, 'cli');
}

/** The generated wrapper of a kind (entry, cli) next to the built file; written once per run. */
function rsWrapper(string $single, string $kind): string
{
    static $written = [];
    $file = dirname($single) . "/rs-test-$kind.php";
    if (!isset($written[$file])) {
        $stats = dirname($single) . '/request-shield-stats.php';
        $load = 'define("REQUEST_SHIELD_DONE", true); require ' . var_export($single, true) . '; if (is_file(' . var_export($stats, true) . ')) { require ' . var_export($stats, true) . '; }';
        $code = $kind === 'cli'
            ? "<?php\n// Generated by tests/helpers.php (rsCli()): the built file's command line, with the statistics file.\n$load\n"
                . "exit(\\CjwNetwork\\RequestShield\\Cli::main(array_values(array_map('strval', \$argv))));\n"
            : "<?php\n// Generated by tests/helpers.php (rsEntry()): the built file and the statistics file, then its bootstrap's search.\n"
                . "(static function (): void {\n    if (defined('REQUEST_SHIELD_DONE')) {\n        return;\n    }\n    $load\n    if (PHP_SAPI === 'cli') {\n        return;\n    }\n"
                . "    \$named = defined('REQUEST_SHIELD_CONFIG') ? constant('REQUEST_SHIELD_CONFIG') : getenv('REQUEST_SHIELD_CONFIG');\n"
                . "    if (is_string(\$named) && \$named !== '') {\n        if (is_file(\$named)) {\n            \\CjwNetwork\\RequestShield\\Shield::protectFile(\$named);\n        }\n        return;\n    }\n"
                . "    foreach ([__DIR__ . '/request-shield.rules', __DIR__ . '/config/request-shield.rules', __DIR__ . '/config/request-shield.php'] as \$file) {\n"
                . "        if (is_file(\$file)) {\n            \\CjwNetwork\\RequestShield\\Shield::protectFile(\$file);\n            return;\n        }\n    }\n})();\n";
        file_put_contents($file, $code);
        $written[$file] = true;
    }
    return $file;
}


/**
 * A test that needs the shipped plugins (the WAF's pages, the statistics, the API, the cache):
 * skipped against the core single file (REQUEST_SHIELD_ENTRY), which has none -- the CI tests
 * the core there; the plugins are tested in the source tree.
 */
function needsPlugins(): void
{
    if (rsSingle() !== null && !class_exists(\CjwNetwork\RequestShield\Waf\WafExtension::class)) {
        skip('needs the shipped plugins: the core single file has none (they are tested in the source tree)');
    }
}

/** A plugin's feature (RSF06-*: dashboard, statistics, live view, API; RSF04-03: the cache) -- needsPlugins() for a whole test. */
function pluginFeature(string $name): bool
{
    return preg_match('/^RSF(06-\d{2}|04-03)\b/', $name) === 1;
}

/**
 * PHP-FPM of the PHP the tests run on (TESTS_PHP_FPM, else php-fpm<major.minor>
 * or php-fpm), or null. For what the built-in server cannot take: it answers
 * methods it does not know (PURGE, PURGEKEYS) with 501 before any script runs.
 */
function fpmBinary(): ?string
{
    $given = getenv('TESTS_PHP_FPM');
    if (is_string($given) && $given !== '') {
        return is_executable($given) ? $given : null;
    }
    $v = PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION;
    foreach (["/usr/sbin/php-fpm$v", "/usr/sbin/php-fpm", dirname(PHP_BINARY, 2) . '/sbin/php-fpm'] as $path) {
        if (is_executable($path)) {
            return $path;
        }
    }
    return null;
}

/**
 * PHP-FPM in the foreground on 127.0.0.1:$port, its files in $dir; returns
 * the process (proc_terminate() ends it) once it listens. The restrictions
 * of TESTS_HOSTING=minimal apply as for serverPhp().
 *
 * @return resource
 */
function startFpm(string $fpm, string $dir, int $port)
{
    $values = getenv('TESTS_HOSTING') === 'minimal' ? "php_admin_value[apc.enabled] = 0\nphp_admin_value[memory_limit] = 64M\n" : '';
    file_put_contents("$dir/fpm.conf", "[global]\nerror_log = $dir/fpm.log\npid = $dir/fpm.pid\n[www]\nlisten = 127.0.0.1:$port\n"
        . "pm = static\npm.max_children = 2\nclear_env = no\ncatch_workers_output = yes\n$values");
    $proc = proc_open(sprintf('exec %s -F -y %s -p %s > %s 2>&1', escapeshellarg($fpm), escapeshellarg("$dir/fpm.conf"), escapeshellarg($dir), escapeshellarg("$dir/fpm.out")), [], $pipes);
    if (!is_resource($proc)) {
        throw new RuntimeException('php-fpm did not start');
    }
    for ($i = 0; $i < 50 && !@fsockopen('127.0.0.1', $port); $i++) {
        usleep(100000);
    }
    return $proc;
}

/**
 * One request to FastCGI on 127.0.0.1:$port, as a web server sends it:
 * $params are the CGI variables (REQUEST_METHOD, SCRIPT_FILENAME,
 * HTTP_* …). Returns [status, headers as sent, body].
 *
 * @param array<string, string> $params
 * @return array{0: int, 1: string, 2: string}
 */
function fcgi(int $port, array $params, string $stdin = ''): array
{
    $f = fsockopen('127.0.0.1', $port, $no, $err, 5);
    if ($f === false) {
        throw new RuntimeException("fastcgi: $err");
    }
    $record = static fn (int $type, string $content): string => pack('CCnnCx', 1, $type, 1, strlen($content), 0) . $content;
    $len = static fn (int $n): string => $n < 128 ? chr($n) : pack('N', $n | 0x80000000);
    $pairs = '';
    foreach ($params as $k => $v) {
        $pairs .= $len(strlen($k)) . $len(strlen($v)) . $k . $v;
    }
    fwrite($f, $record(1, pack('nCx5', 1, 0)) . $record(4, $pairs) . $record(4, '') . ($stdin !== '' ? $record(5, $stdin) : '') . $record(5, ''));
    $out = '';
    while (!feof($f)) {
        $head = fread($f, 8);
        if ($head === false || strlen($head) < 8) {
            break;
        }
        $h = unpack('Cversion/Ctype/nid/nlength/Cpadding', $head);
        $content = $h['length'] > 0 ? (string) stream_get_contents($f, $h['length']) : '';
        if ($h['padding'] > 0) {
            fread($f, $h['padding']);
        }
        if ($h['type'] === 6) {
            $out .= $content;
        } elseif ($h['type'] === 3) {
            break;
        }
    }
    fclose($f);
    [$headers, $body] = explode("\r\n\r\n", $out, 2) + ['', ''];
    $status = preg_match('/^Status: (\d{3})/mi', $headers, $m) === 1 ? (int) $m[1] : 200;
    return [$status, $headers, $body];
}
