<?php
/**
 * The showcase's words, German and English. The tries' sentences are the
 * comments of the rules' expect lines (English); 'tries' gives them in
 * German -- a test holds that every try has its German sentence.
 *
 * @copyright Copyright (C) 2026 JAC Systeme GmbH, CJW Network
 * @license MIT, see LICENSE
 */

declare(strict_types=1);

return [
    'de' => [
        'title' => 'request-shield — Bots raus, Menschen rein',
        'nav' => ['what' => 'Was er tut', 'rules' => 'Die Regeln', 'try' => 'Ausprobieren', 'install' => 'Installation'],
        'heroEyebrow' => 'Dein freundlicher Türsteher für PHP-Websites',
        'heroTitle' => 'Bots raus.<br><span>Menschen rein.</span>',
        'heroLead' => 'request-shield lässt deine Besucher herein und schickt Scanner, Spam und hektische Bots höflich weiter — bevor WordPress, Symfony oder dein CMS auch nur aufwachen. Ohne Captcha, ohne Cloud, in einer einzigen Datei.',
        'mascot' => 'Hallo! Ich passe auf deine Website auf.',
        'heroTry' => 'Live ausprobieren',
        'heroRules' => 'So einfach sind die Regeln',
        'streamTitle' => 'Was ich gerade entscheide — live',
        'stats' => [['~10 µs', 'pro Anfrage'], ['0', 'Abhängigkeiten'], ['1', 'Datei'], ['PHP 8.0+', 'läuft überall']],
        'promiseTitle' => 'Schutz, der niemanden ausschließt',
        'promises' => [
            ['bi-universal-access-circle', 'Barrierefrei', 'Kein Bilderrätsel, kein Audio-Captcha, kein Klick auf Ampeln. Der Check läuft von selbst — niemand muss etwas lesen, hören oder bedienen, und ein Screenreader sagt an, wenn er nicht weiterkommt. Er braucht nur JavaScript und Cookies.'],
            ['bi-eye-slash', 'Ohne Tracking', 'Kein Tracking-Cookie, kein Profil. Nur ein kurzer, signierter Pass für die Sicherheit — gebunden an Adressgruppe und Browser, nach einer Stunde vorbei.'],
            ['bi-shield-lock', 'Ohne Drittanbieter', 'Kein Google, kein Cloudflare, kein CDN — der Check läuft auf deinem Server. Nur die Prüfung echter Crawler fragt einen DNS-Resolver, und die lässt sich abschalten.'],
            ['bi-house-heart', 'Auf deinem eigenen Server', 'Eine PHP-Datei, deine Regeln, deine Logs. Läuft mit PHP 8.0 und sonst nichts — auch auf einfachem Shared Hosting; mit einem beschreibbaren Ordner mit allem, ohne ihn mit den Regeln.'],
        ],
        'whatTitle' => 'Was er tut — ohne dass du etwas merkst',
        'whatLead' => 'Die meisten Anfragen an eine Website kommen nicht von Menschen. request-shield sortiert sie aus, bevor sie Rechenzeit kosten.',
        'features' => [
            ['bi-bug', 'Scanner laufen ins Leere', 'Wer nach .env, .git, phpMyAdmin oder alten Backups sucht, bekommt ein schlichtes 404 — eingebaut, ohne eine Zeile Konfiguration.'],
            ['bi-braces', 'Parameter mit Typen', 'Eine Seitennummer ist eine Zahl, eine Suche ist Text. Alles andere ist 404 — und Angriffsmuster werden nur dort gesucht, wo freier Text steht.'],
            ['bi-speedometer2', 'Bots im Takt', 'Wer zu schnell klickt, bekommt einen unsichtbaren Browser-Check. Menschen merken nichts, Skripte zahlen Rechenzeit.'],
            ['bi-envelope-check', 'Formulare nur von dir', 'Kontaktformulare nehmen nur Post von deinen eigenen Seiten an. Spam von fremden Seiten kommt nicht an.'],
            ['bi-building-lock', 'Zugänge nach Netzwerk', 'Der Admin-Bereich nur aus dem Büro, die Statistik nur vom Server selbst — eine Zeile pro Regel.'],
            ['bi-robot', 'Crawler mit Ausweis', 'Googlebot ist nur Googlebot, wenn er von Googles Adressen kommt. KI-Trainings-Crawler sperrst du mit einem Wort.'],
        ],
        'rulesTitle' => 'Die Regeln: lesbar wie ein Zettel an der Tür',
        'rulesLead' => 'Das ist die komplette Regeldatei dieser Seite — mit Werten, wie sie eine echte Website nutzt. Links die Regel, rechts was sie bedeutet.',
        'rulesNote' => 'Unter jeder Regel steht im Original ein Beispiel (<code>expect</code>). <code>request-shield test</code> prüft sie alle — die Karten unten sind genau diese Beispiele.',
        'tryTitle' => 'Probier es aus',
        'tryLead' => 'Klick dich durch: Jeder Knopf schickt eine echte Anfrage, und der Shield antwortet sofort. Keine Sorge — jede Karte ist ein eigener Besucher, du sperrst dich nicht aus.',
        'tryAll' => 'Alle nacheinander senden',
        'send' => 'Senden',
        'sent' => 'Nochmal',
        'expected' => 'erwartet',
        'from' => 'von',
        'simulated' => 'Intern entschieden: Kein Browser darf einen fremden Origin fälschen — der Server prüft genau diese Anfrage mit den echten Regeln.',
        'passCard' => 'Mit Pass: Öffne den Login in einem neuen Tab. Der unsichtbare Check läuft eine Sekunde, danach kommst du direkt rein.',
        'openLogin' => 'Login öffnen',
        'groups' => [
            'scan' => ['Scanner & Angreifer', 'Eingebaut. Nichts zu konfigurieren.'],
            'params' => ['Parameter mit Typen', 'Was die Seite nicht kennt, gibt es nicht.'],
            'pace' => ['Bots im Takt', '60 Seiten pro Minute sind viel für einen Menschen — und wenig für einen Bot.'],
            'forms' => ['Formulare', 'Post nur dorthin, wo ein Formular ist, und nur von deinen Seiten.'],
            'access' => ['Zugänge', 'Wer darf wohin — nach Adresse, mit Check, oder gar nicht.'],
        ],
        'burstTitle' => 'Ein Bot schickt 125 Seitenaufrufe in einer Minute',
        'burstLead' => 'Bis 60: durch. Ab 61: der unsichtbare Browser-Check (ein Mensch merkt ihn nicht, ein Skript muss rechnen). Ab 121: Pause.',
        'burstGo' => '125 Anfragen senden',
        'burstLegend' => ['durch', 'Browser-Check', 'Pause'],
        'burstLog' => 'Die Anfragen anzeigen',
        'burstFrom' => 'alle vom selben Besucher',
        'say' => ['answered' => 'Herein! Die Seite kommt an.', 'check' => 'Kurzer, unsichtbarer Check — Menschen merken nichts.', '403' => 'Freundlich, aber bestimmt: kein Zutritt.',
            '404' => 'Hier gibt es nichts zu holen.', '405' => 'Das geht an dieser Stelle nicht.', '429' => 'Kurze Pause, bitte.', '400' => 'Das ist keine gültige Anfrage.'],
        'details' => 'Details',
        'outcome' => ['answered' => 'durchgelassen', 'check' => 'Browser-Check', '403' => 'abgewiesen', '404' => 'gibt es nicht', '405' => 'nicht erlaubt', '429' => 'Pause', '400' => 'kaputte Anfrage'],
        'checkTitle' => 'Der Browser-Check, den niemand sieht',
        'checkSteps' => [
            ['bi-hourglass-split', 'Der Browser bekommt eine kleine Rechenaufgabe', 'Signiert, an seine Adresse gebunden, nach wenigen Minuten abgelaufen.'],
            ['bi-cpu', 'Er löst sie in einem Bruchteil einer Sekunde', 'Ein Mensch sieht kurz „Einen Moment …“. Kein Bild, kein Klick, kein Rätsel.'],
            ['bi-ticket-perforated', 'Er bekommt einen Pass', 'Ein signiertes Cookie. Damit kommen die nächsten Seiten direkt durch — für einen Bot kostet jede neue Adresse wieder Rechenzeit.'],
        ],
        'checkTry' => 'Selbst erleben: Login öffnen',
        'checkNote' => 'Barrierefrei, ohne Tracking, ohne Drittanbieter — läuft auf deinem eigenen Server.',
        'installTitle' => 'In drei Schritten auf deiner Website',
        'install' => [
            ['Datei hochladen', 'Eine einzige PHP-Datei neben deine Website — signiert, ohne Composer.'],
            ['Eine Zeile einfügen', 'In die php.ini, .user.ini oder als erste Zeile deines index.php.'],
            ['Regeln schreiben', 'Starte mit den mitgelieferten Regeln. Jede weitere ist eine Zeile.'],
        ],
        'installMonitor' => 'Erst beobachten: <code>set mode monitor</code> protokolliert, was der Shield tun würde — und weist niemanden ab.',
        'footer' => 'request-shield · MIT-Lizenz · eine Demo, die auf deinem Rechner läuft',
        'notes' => [
            'every rule\'s name starts with SHOW-: decisions and the log name it' => 'jede Regel heißt SHOW-…: Entscheidungen und Log nennen den Namen',
            'this rule set\'s own version' => 'die Version dieser Regeln',
            'the proxy in front: from it, X-Forwarded-For names the visitor' => 'der Proxy davor: von ihm nennt X-Forwarded-For den Besucher',
            'The page sends each try as a visitor of its own (X-Forwarded-For from this' => 'Die Seite schickt jeden Versuch als eigenen Besucher (X-Forwarded-For von dieser',
            'machine), so a try never blocks you. A real site trusts its proxy here.' => 'Maschine) — so sperrt dich kein Versuch aus. Eine echte Website nennt hier ihren Proxy.',
            'Built in, without a line: scanners\' paths, path traversal, broken requests.' => 'Eingebaut, ohne eine Zeile: Pfade der Scanner, Path-Traversal, kaputte Anfragen.',
            'utm_*, fbclid, gclid: newsletter and ad links keep working' => 'utm_*, fbclid, gclid: Newsletter- und Werbelinks funktionieren weiter',
            'SQL injection, XSS, shell commands -- in the free text only' => 'SQL-Injection, XSS, Shell-Befehle — nur im freien Text',
            'the parameters the site knows, and their types' => 'die Parameter, die die Seite kennt, und ihre Typen',
            'any other parameter, or a wrong type: 404' => 'jeder andere Parameter oder ein falscher Typ: 404',
            'per visitor: 60 a minute pass silently, then the invisible check, past 120 a pause' => 'pro Besucher: 60 pro Minute laufen still durch, dann der unsichtbare Check, über 120 eine Pause',
            'forms may only be sent to the contact page' => 'Formulare dürfen nur an die Kontaktseite',
            '... and only from the site\'s own pages' => '… und nur von den eigenen Seiten',
            'the admin area: only the office network' => 'der Admin-Bereich: nur aus dem Büronetz',
            'the login: every visitor is checked (invisibly) first' => 'der Login: jeder Besucher wird zuerst (unsichtbar) geprüft',
            'an address kept out for good' => 'eine Adresse, die dauerhaft draußen bleibt',
            'verified AI training crawlers: no' => 'verifizierte KI-Trainings-Crawler: nein',
        ],
        'tries' => [
            'A visitor reads the front page' => 'Ein Besucher liest die Startseite',
            'A scanner looks for your passwords' => 'Ein Scanner sucht deine Passwörter',
            '... for your source code' => '… deinen Quellcode',
            '... for a database tool' => '… ein Datenbank-Werkzeug',
            '... for a forgotten backup' => '… ein vergessenes Backup',
            'SQL injection in the search' => 'SQL-Injection in der Suche',
            'A newsletter link: welcome' => 'Ein Newsletter-Link: willkommen',
            'A page number that is a number' => 'Eine Seitennummer, die eine Zahl ist',
            'A page "number" that is not one' => 'Eine „Seitennummer“, die keine ist',
            'A parameter the site does not know' => 'Ein Parameter, den die Seite nicht kennt',
            '61 pages in a minute: the invisible check' => '61 Seiten in einer Minute: der unsichtbare Check',
            '121 in a minute: a pause' => '121 in einer Minute: Pause',
            'A POST where no form is' => 'Ein POST, wo kein Formular ist',
            'The contact form, from the site' => 'Das Kontaktformular, von der eigenen Seite',
            'The contact form, sent from elsewhere' => 'Das Kontaktformular, von einer fremden Seite',
            'The admin area, from the office' => 'Der Admin-Bereich, aus dem Büro',
            'The admin area, from anywhere else' => 'Der Admin-Bereich, von woanders',
            'The login: checked first' => 'Der Login: erst der Check',
            '... with a pass: straight in' => '… mit Pass: direkt rein',
            'An address on the deny list' => 'Eine Adresse auf der Sperrliste',
            'The shield\'s own pages, from outside' => 'Die Seiten des Shields, von außen',
        ],
    ],
    'en' => [
        'title' => 'request-shield — bots out, people in',
        'nav' => ['what' => 'What it does', 'rules' => 'The rules', 'try' => 'Try it', 'install' => 'Install'],
        'heroEyebrow' => 'A friendly doorkeeper for PHP websites',
        'heroTitle' => 'Bots out.<br><span>People in.</span>',
        'heroLead' => 'request-shield lets your visitors in and politely sends scanners, spam and hasty bots on their way — before WordPress, Symfony or your CMS even wake up. No captcha, no cloud, one single file.',
        'mascot' => 'Hello! I look after your website.',
        'heroTry' => 'Try it live',
        'heroRules' => 'See how simple the rules are',
        'streamTitle' => 'What I decide right now — live',
        'stats' => [['~10 µs', 'per request'], ['0', 'dependencies'], ['1', 'file'], ['PHP 8.0+', 'runs anywhere']],
        'promiseTitle' => 'Protection that shuts nobody out',
        'promises' => [
            ['bi-universal-access-circle', 'Accessible', 'No picture puzzles, no audio captcha, no clicking traffic lights. The check runs by itself — nobody has to read, hear or operate anything, and a screen reader is told when it cannot go on. All it needs is JavaScript and cookies.'],
            ['bi-eye-slash', 'No tracking', 'No tracking cookie, no profile. Only a short, signed pass for security — tied to the address group and the browser, gone after an hour.'],
            ['bi-shield-lock', 'No third party', 'No Google, no Cloudflare, no CDN — the check runs on your server. Only the check of real crawlers asks a DNS resolver, and it can be switched off.'],
            ['bi-house-heart', 'On your own server', 'One PHP file, your rules, your logs. Runs on PHP 8.0 and nothing else — simple shared hosting included; with a writable folder in full, without one with the rules.'],
        ],
        'whatTitle' => 'What it does — without anyone noticing',
        'whatLead' => 'Most requests to a website do not come from people. request-shield sorts them out before they cost computing time.',
        'features' => [
            ['bi-bug', 'Scanners hit a wall', 'Whoever looks for .env, .git, phpMyAdmin or old backups gets a plain 404 — built in, without a line of configuration.'],
            ['bi-braces', 'Parameters with types', 'A page number is a number, a search is text. Anything else is a 404 — and attack patterns are looked for only where free text is.'],
            ['bi-speedometer2', 'Bots kept in step', 'Whoever clicks too fast gets an invisible browser check. People notice nothing, scripts pay in computing time.'],
            ['bi-envelope-check', 'Forms from your site only', 'Contact forms only take what your own pages send. Spam from other sites never arrives.'],
            ['bi-building-lock', 'Access by network', 'The admin area from the office only, the statistics from the server itself — one line per rule.'],
            ['bi-robot', 'Crawlers that prove who they are', 'Googlebot is Googlebot only from Google\'s addresses. AI training crawlers are kept out with one word.'],
        ],
        'rulesTitle' => 'The rules: as readable as a note on the door',
        'rulesLead' => 'This is this site\'s complete rule file — with values a real website uses. On the left the rule, on the right what it means.',
        'rulesNote' => 'In the file, every rule has an example below it (<code>expect</code>). <code>request-shield test</code> checks them all — the cards below are exactly these examples.',
        'tryTitle' => 'Try it',
        'tryLead' => 'Click your way through: every button sends a real request, and the shield answers at once. Don\'t worry — each card is a visitor of its own, you never lock yourself out.',
        'tryAll' => 'Send them all, one after another',
        'send' => 'Send',
        'sent' => 'Again',
        'expected' => 'expected',
        'from' => 'from',
        'simulated' => 'Decided on the server: no browser may forge another site\'s Origin — the server checks exactly this request with the real rules.',
        'passCard' => 'With a pass: open the login in a new tab. The invisible check runs for a second, then you are in.',
        'openLogin' => 'Open the login',
        'groups' => [
            'scan' => ['Scanners & attackers', 'Built in. Nothing to configure.'],
            'params' => ['Parameters with types', 'What the site does not know does not exist.'],
            'pace' => ['Bots kept in step', '60 pages a minute is a lot for a person — and little for a bot.'],
            'forms' => ['Forms', 'A POST only where a form is, and only from your pages.'],
            'access' => ['Access', 'Who may go where — by address, with a check, or not at all.'],
        ],
        'burstTitle' => 'A bot sends 125 page views in a minute',
        'burstLead' => 'Up to 60: through. From 61: the invisible browser check (a person does not notice, a script has to compute). From 121: a pause.',
        'burstGo' => 'Send 125 requests',
        'burstLegend' => ['through', 'browser check', 'pause'],
        'burstLog' => 'Show the requests',
        'burstFrom' => 'all from one visitor',
        'say' => ['answered' => 'Come in! The page is delivered.', 'check' => 'A quick, invisible check — people notice nothing.', '403' => 'Friendly but firm: no entry.',
            '404' => 'Nothing to find here.', '405' => 'That is not possible here.', '429' => 'A short pause, please.', '400' => 'That is no valid request.'],
        'details' => 'Details',
        'outcome' => ['answered' => 'let through', 'check' => 'browser check', '403' => 'refused', '404' => 'not found', '405' => 'not allowed', '429' => 'pause', '400' => 'broken request'],
        'checkTitle' => 'The browser check nobody sees',
        'checkSteps' => [
            ['bi-hourglass-split', 'The browser gets a small sum to work out', 'Signed, bound to its address, expired after a few minutes.'],
            ['bi-cpu', 'It solves it in a fraction of a second', 'A person briefly sees "One moment …". No picture, no click, no puzzle.'],
            ['bi-ticket-perforated', 'It gets a pass', 'A signed cookie. The next pages come straight through — for a bot, every new address costs computing time again.'],
        ],
        'checkTry' => 'See for yourself: open the login',
        'checkNote' => 'Accessible, no tracking, no third party — it runs on your own server.',
        'installTitle' => 'On your website in three steps',
        'install' => [
            ['Upload one file', 'A single PHP file next to your website — signed, no Composer.'],
            ['Add one line', 'To php.ini, .user.ini, or as the first line of your index.php.'],
            ['Write your rules', 'Start with the rules that come with it. Every further one is a line.'],
        ],
        'installMonitor' => 'Watch first: <code>set mode monitor</code> logs what the shield would do — and refuses nobody.',
        'footer' => 'request-shield · MIT licence · a demo running on your own machine',
        'notes' => [],
        'tries' => [],
    ],
];
