<?php
/**
 * The showcase's words, German and English. The tries' sentences are the
 * comments of the rules' expect lines (English); 'tries' gives them in
 * German -- a test holds that every try has its German sentence.
 *
 * @copyright Copyright (C) 2026 JAC Systeme GmbH, CJW Network
 * @license MIT, see LICENSE
 */

declare(strict_types=1);

return [
    'de' => [
        'title' => 'request-shield — Bots raus, Menschen rein',
        'nav' => ['what' => 'Was er tut', 'rules' => 'Die Regeln', 'try' => 'Ausprobieren', 'exponential' => 'Exponential', 'install' => 'Installation'],
        'heroEyebrow' => 'Dein freundlicher Türsteher für PHP-Websites',
        'heroTitle' => 'Bots raus.<br><span>Menschen rein.</span>',
        'heroLead' => 'request-shield lässt deine Besucher herein und schickt Scanner, Spam und hektische Bots höflich weiter — bevor WordPress, Symfony oder dein CMS auch nur aufwachen. Ohne Captcha, ohne Cloud, in einer einzigen Datei.',
        'mascot' => 'Hallo! Ich passe auf deine Website auf.',
        'heroTry' => 'Live ausprobieren',
        'heroRules' => 'So einfach sind die Regeln',
        'streamTitle' => 'Was ich gerade entscheide — live',
        'stats' => [['~10 µs', 'pro Anfrage'], ['0', 'Abhängigkeiten'], ['1', 'Datei'], ['PHP 8.0+', 'läuft überall']],
        'promiseTitle' => 'Schutz, der niemanden ausschließt',
        'promises' => [
            ['bi-universal-access-circle', 'Barrierefrei', 'Kein Bilderrätsel, kein Audio-Captcha, kein Klick auf Ampeln. Der Check läuft von selbst — niemand muss etwas lesen, hören oder bedienen, und ein Screenreader sagt an, wenn er nicht weiterkommt. Er braucht nur JavaScript und Cookies.'],
            ['bi-eye-slash', 'Ohne Tracking', 'Kein Tracking-Cookie, kein Profil. Nur ein kurzer, signierter Pass für die Sicherheit — gebunden an Adressgruppe und Browser, nach einer Stunde vorbei.'],
            ['bi-shield-lock', 'Ohne Drittanbieter', 'Kein Google, kein Cloudflare, kein CDN — der Check läuft auf deinem Server. Nur die Prüfung echter Crawler fragt einen DNS-Resolver, und die lässt sich abschalten.'],
            ['bi-house-heart', 'Auf deinem eigenen Server', 'Eine PHP-Datei, deine Regeln, deine Logs. Läuft mit PHP 8.0 und sonst nichts — auch auf einfachem Shared Hosting; mit einem beschreibbaren Ordner mit allem, ohne ihn mit den Regeln.'],
        ],
        'whatTitle' => 'Was er tut — ohne dass du etwas merkst',
        'whatLead' => 'Die meisten Anfragen an eine Website kommen nicht von Menschen. request-shield sortiert sie aus, bevor sie Rechenzeit kosten.',
        'features' => [
            ['bi-bug', 'Scanner laufen ins Leere', 'Wer nach .env, .git, phpMyAdmin oder alten Backups sucht, bekommt ein schlichtes 404 — eingebaut, ohne eine Zeile Konfiguration.'],
            ['bi-braces', 'Parameter mit Typen', 'Eine Seitennummer ist eine Zahl, eine Suche ist Text. Alles andere ist 404 — und Angriffsmuster werden nur dort gesucht, wo freier Text steht.'],
            ['bi-speedometer2', 'Bots im Takt', 'Wer zu schnell klickt, bekommt einen unsichtbaren Browser-Check. Menschen merken nichts, Skripte zahlen Rechenzeit.'],
            ['bi-envelope-check', 'Formulare nur von dir', 'Kontaktformulare nehmen nur Post von deinen eigenen Seiten an. Spam von fremden Seiten kommt nicht an.'],
            ['bi-building-lock', 'Zugänge nach Netzwerk', 'Der Admin-Bereich nur aus dem Büro, die Statistik nur vom Server selbst — eine Zeile pro Regel.'],
            ['bi-robot', 'Crawler mit Ausweis', 'Googlebot ist nur Googlebot, wenn er von Googles Adressen kommt. KI-Trainings-Crawler sperrst du mit einem Wort.'],
        ],
        'rulesTitle' => 'Die Regeln: lesbar wie ein Zettel an der Tür',
        'rulesLead' => 'Das ist die komplette Regeldatei dieser Seite — mit Werten, wie sie eine echte Website nutzt. Links die Regel, rechts was sie bedeutet.',
        'rulesNote' => 'Unter jeder Regel steht im Original ein Beispiel (<code>expect</code>). <code>request-shield test</code> prüft sie alle — die Karten unten sind genau diese Beispiele.',
        'tryTitle' => 'Probier es aus',
        'tryLead' => 'Klick dich durch: Jeder Knopf schickt eine echte Anfrage, und der Shield antwortet sofort. Keine Sorge — jede Karte ist ein eigener Besucher, du sperrst dich nicht aus.',
        'tryAll' => 'Alle nacheinander senden',
        'send' => 'Senden',
        'sent' => 'Nochmal',
        'expected' => 'erwartet',
        'from' => 'von',
        'simulated' => 'Intern entschieden: Kein Browser darf einen fremden Origin fälschen — der Server prüft genau diese Anfrage mit den echten Regeln.',
        'passCard' => 'Mit Pass: Öffne den Login in einem neuen Tab. Der unsichtbare Check läuft eine Sekunde, danach kommst du direkt rein.',
        'openLogin' => 'Login öffnen',
        'groups' => [
            'scan' => ['Scanner & Angreifer', 'Eingebaut. Nichts zu konfigurieren.'],
            'params' => ['Parameter mit Typen', 'Was die Seite nicht kennt, gibt es nicht.'],
            'pace' => ['Bots im Takt', '60 Seiten pro Minute sind viel für einen Menschen — und wenig für einen Bot.'],
            'self' => ['Seiten, die selbst mitzählen', 'Die Suche und der Login zählen mit. Wer übertreibt, wartet — und jedes Mal doppelt so lang.'],
            'forms' => ['Formulare', 'Post nur dorthin, wo ein Formular ist, und nur von deinen Seiten.'],
            'api' => ['Eine API mit JSON und XML', 'Ein Formular schickt JSON an die API, andere Programme lesen Produkte als JSON oder XML. Ihre Regeln stehen in einem eigenen Block: match /api/** { … }'],
            'access' => ['Zugänge', 'Wer darf wohin — nach Adresse, mit Check, oder gar nicht.'],
        ],
        'burstTitle' => 'Ein Bot schickt 125 Seitenaufrufe in einer Minute',
        'burstLead' => 'Bis 60: durch. Ab 61: der unsichtbare Browser-Check (ein Mensch merkt ihn nicht, ein Skript muss rechnen). Ab 121: Pause.',
        'burstGo' => '125 Anfragen senden',
        'burstLegend' => ['durch', 'Browser-Check', 'Pause'],
        'burstLog' => 'Die Anfragen anzeigen',
        'exp' => [
            'title' => 'Beispiel: eine Exponential-Website',
            'lead' => 'Exponential (das CMS mit Siteaccesses, URL-Aliasen und Admin-Oberfläche) bekommt, was jedes CMS bekommt: Scraper zählen Knotennummern durch, Scanner fragen nach settings/site.ini, Bots posten überallhin und hämmern auf die Suche. Der Kernel braucht für jede dieser Anfragen 20 bis 150 ms PHP und Datenbank — der Shield antwortet vorher.',
            'how' => 'Drei Regeldateien in examples/exponential und eine Zeile in config.php:',
            'decided' => 'Diese Beispiele entscheidet der Server mit den echten Exponential-Regeln (Admin unter /admin, scharf geschaltet), genau wie request-shield test — ohne mitzuzählen. Eine zweite Website lässt sich in dieser Seite nicht echt aufrufen.',
            'checkAll' => 'Alle prüfen', 'check' => 'Prüfen', 'rules' => 'Die Regeln', 'why' => 'Warum jede Regel: docs/use-cases/exponential.md', 'summary' => '%d von %d wie erwartet',
            'groups' => ['The site' => 'Die Website', 'System URLs in the frontend' => 'Systemadressen im Frontend', 'Forms' => 'Formulare', 'Search' => 'Suche',
                'Pace and bans' => 'Tempo und Sperren', 'The shield itself' => 'Der Shield selbst', 'Admin (/admin)' => 'Admin (/admin)'],
        ],
        'api' => [
            'formTitle' => 'Ein Formular, das JSON an die API schickt', 'formLead' => 'Wie bei einer modernen Website: Das Formular sendet per fetch() ein JSON an POST /api/v1/messages. Die Schritte darunter sind echt.',
            'name' => 'Name', 'message' => 'Nachricht', 'send' => 'Senden', 'bot' => 'Als Bot senden (ohne Browser, neue Adresse)', 'forget' => 'Pass vergessen',
            'sent' => 'Gesendet: POST /api/v1/messages, Content-Type: application/json', 'challenge' => 'Antwort 429: Die API verlangt den Check — die Aufgabe steht als JSON im Header Request-Shield-Challenge',
            'solved' => 'Der Browser löst die Aufgabe unsichtbar: %d ms', 'resend' => 'Erneut gesendet, mit der Lösung im Header Request-Shield-Solution',
            'done' => 'Antwort %d: %s', 'pass' => 'Der Browser hat jetzt einen Pass (Cookie, 1 Stunde): Die nächste Nachricht geht direkt durch.',
            'botDone' => 'Ein Skript ohne Browser bekommt nur das: 429 und eine Aufgabe, die es für jede Nachricht neu rechnen müsste.', 'forgotten' => 'Pass vergessen — die nächste Nachricht verlangt wieder den Check.',
            'whyTitle' => 'Warum diese Regeln?',
            'why' => [
                ['api-path /api/**', 'Ein Programm kann keine Check-Seite anzeigen. Auf /api/** antwortet der Shield deshalb mit JSON: den Check als Aufgabe im Header, eine Ablehnung (404, 403, 429) als JSON mit Referenz.'],
                ['allow POST', 'Die API nimmt GET und POST an. PUT, DELETE und andere Methoden werden abgewiesen (405), bevor PHP überhaupt läuft.'],
                ['query page int · limit int · format json|xml', 'Seite und Anzahl sind Zahlen, das Format json oder xml. Jeder andere Parameter oder Wert: 404 — Angriffsmuster finden keinen Platz.'],
                ['limit api 30/min', 'Jeder Besucher darf 30 Aufrufe pro Minute. Danach 429 mit Retry-After: Ein Scraper liest den Katalog nicht in Sekunden aus.'],
                ['challenge POST', 'Jedes Schreiben braucht einen Pass. Ein Browser löst die Aufgabe unsichtbar und einmal pro Stunde; ein Spam-Skript muss für jede Nachricht neu rechnen.'],
                ['post-origin — hier nicht', 'Für APIs gilt post-origin nicht, denn Programme senden kein Origin. Gegen fremde Webseiten schützt hier der Browser: JSON von einer fremden Seite verlangt einen CORS-Preflight, den die API nicht beantwortet.'],
                ['Der Inhalt', 'Das JSON selbst prüft der Shield nicht. Die API prüft Typ, Felder und Längen selbst (415, 422) — das bleibt ihre Aufgabe.'],
            ],
        ],
        'self' => [
            'searchTitle' => 'Eine Suche, die mitzählt', 'searchLead' => '5 Suchen pro Minute für jeden Besucher. Danach eine Pause — 5 Sekunden, dann 10, 20, 40 …',
            'searchPlaceholder' => 'Suchbegriff', 'searchGo' => 'Suchen', 'hits' => '%d Treffer für „%s“',
            'loginTitle' => 'Ein Login, der falsche Passwörter zählt', 'loginLead' => '3 falsche Passwörter in 15 Minuten gehen durch, danach eine Pause — 5 Sekunden, dann 10, 20, 40 … Ein richtiges Passwort zählt nicht.',
            'user' => 'Benutzer', 'password' => 'Passwort', 'pwHint' => 'Das richtige Passwort ist „sesam“.', 'loginGo' => 'Anmelden',
            'wrong' => 'Falsches Passwort.', 'welcome' => 'Willkommen, demo!', 'pause' => 'Pause — der Shield antwortet statt der Seite. Wieder möglich in %d s.', 'limit' => 'Limit erreicht — der Shield antwortet für die Seite, und eine Pause beginnt.', 'legendLimit' => 'Limit erreicht, neue Pause',
            'botGo' => 'Bot-Modus: 60 Sekunden, jede Sekunde ein Versuch', 'botStop' => 'Anhalten', 'newVisitor' => 'Neuer Besucher',
            'botSummary' => '%d von %d Versuchen kamen bei der Seite an.', 'blockFor' => 'Pause %d s', 'legendReached' => 'kam an', 'legendRefused' => 'abgewiesen',
            'visitor' => 'Besucher: X-Forwarded-For %s',
        ],
        'burstFrom' => 'alle vom selben Besucher',
        'say' => ['answered' => 'Herein! Die Seite kommt an.', 'check' => 'Kurzer, unsichtbarer Check — Menschen merken nichts.', '403' => 'Freundlich, aber bestimmt: kein Zutritt.',
            '404' => 'Hier gibt es nichts zu holen.', '405' => 'Das geht an dieser Stelle nicht.', '429' => 'Kurze Pause, bitte.', '400' => 'Das ist keine gültige Anfrage.'],
        'details' => 'Details',
        'outcome' => ['passes' => 'durchgelassen', 'uncached' => 'durch, nicht gecacht', 'answered' => 'durchgelassen', 'check' => 'Browser-Check', '403' => 'abgewiesen', '404' => 'gibt es nicht', '405' => 'nicht erlaubt', '429' => 'Pause', '400' => 'kaputte Anfrage'],
        'checkTitle' => 'Der Browser-Check, den niemand sieht',
        'checkSteps' => [
            ['bi-hourglass-split', 'Der Browser bekommt eine kleine Rechenaufgabe', 'Signiert, an seine Adresse gebunden, nach wenigen Minuten abgelaufen.'],
            ['bi-cpu', 'Er löst sie in einem Bruchteil einer Sekunde', 'Ein Mensch sieht kurz „Einen Moment …“. Kein Bild, kein Klick, kein Rätsel.'],
            ['bi-ticket-perforated', 'Er bekommt einen Pass', 'Ein signiertes Cookie. Damit kommen die nächsten Seiten direkt durch — für einen Bot kostet jede neue Adresse wieder Rechenzeit.'],
        ],
        'checkTry' => 'Selbst erleben: Login öffnen',
        'checkNote' => 'Barrierefrei, ohne Tracking, ohne Drittanbieter — läuft auf deinem eigenen Server.',
        'installTitle' => 'In drei Schritten auf deiner Website',
        'install' => [
            ['Datei hochladen', 'Lege request-shield.php und deine Regeln in einen eigenen Ordner — außerhalb des Webroots, damit niemand sie im Browser abrufen kann. Daneben legt der Shield seinen Ordner .request-shield/ an (Zähler, Schlüssel); der Ordner muss beschreibbar sein.',
                "/home/example/\n├── request-shield/            ← neu, außerhalb des Webroots\n│   ├── request-shield.php     ← die eine Datei\n│   └── request-shield.rules   ← deine Regeln (Schritt 3)\n└── public_html/               ← deine Website, wie bisher"],
            ['Einbinden', 'Wähle einen Weg. auto_prepend_file (.htaccess oder .user.ini) schützt jede PHP-Datei der Website; require nur, was durch diese Datei läuft.', ''],
            ['Regeln schreiben und prüfen', 'Fang mit wenigen Zeilen an und lass den Shield erst beobachten. Der Befehl prüft die Regeln und sagt, was dein Hosting kann.',
                "# request-shield.rules — neben request-shield.php\ninclude @tracking                          # Newsletter- und Werbelinks funktionieren weiter\ninclude @attacks                           # SQL-Injection, XSS … im freien Text\nlimit requests 120/min challenge-at 60     # über 60 pro Minute: der unsichtbare Check\nrestrict /admin/** to 192.0.2.0/24         # der Admin-Bereich: nur aus dem Büro\nset mode monitor                           # erst beobachten; später: set mode enforce\nset log /home/example/request-shield/shield.log   # hier steht, was er getan hätte"],
        ],
        'installCheck' => "# im Ordner request-shield/, per SSH\nphp request-shield.php check request-shield.rules\n\n# was er getan hätte, live mitlesen\ntail -f shield.log | grep monitor-",
        'installWays' => [
            ['.htaccess', "# .htaccess im Webroot (public_html/) — Apache mit mod_php, LiteSpeed\nphp_value auto_prepend_file /home/example/request-shield/request-shield.php",
                'Fehler 500 nach dem Speichern? Dann läuft PHP als FPM — nimm stattdessen .user.ini.'],
            ['.user.ini', "; .user.ini im Webroot (public_html/) — PHP-FPM, LiteSpeed LSAPI\nauto_prepend_file = /home/example/request-shield/request-shield.php",
                'PHP liest .user.ini erst nach ein paar Minuten neu (user_ini.cache_ttl, meist 5 Minuten).'],
            ['index.php', "<?php\n// ganz oben in public_html/index.php — vor allem anderen\nrequire '/home/example/request-shield/request-shield.php';\n\n// … ab hier dein Code wie bisher",
                'Für Seiten mit einem Front-Controller (Symfony, Laravel, Exponential). Die Regeln findet der Shield neben der Datei; einen anderen Ort nennt define(\'REQUEST_SHIELD_CONFIG\', \'…/meine.rules\') vor dem require.'],
            ['WordPress', "<?php\n// ganz oben in wp-config.php, direkt nach <?php\nrequire '/home/example/request-shield/request-shield.php';\n\n// … define( 'DB_NAME', … ); wie bisher",
                'Oder per .htaccess / .user.ini: Dann ist auch jede PHP-Datei geschützt, die WordPress nicht selbst lädt.'],
        ],
        'copy' => 'Kopieren', 'copied' => 'Kopiert',
        'installLogTitle' => 'So sieht das Log im Monitor-Modus aus — echt, mit genau diesen Regeln:',
        'installLog' => "2026-10-07T21:09:33+00:00 198.51.100.0/24 monitor-reject 404 \"blocked path\" rule=SCAN-HIDDEN \"GET http://www.example.org/index.php/.env\" \"Mozilla/5.0 (compatible; Scanner/1.0)\"\n2026-10-07T21:09:33+00:00 203.0.113.0/24 monitor-reject 403 \"attack\" rule=ATK-SQL-UNION \"GET http://www.example.org/index.php?q=1%27%20UNION%20SELECT%20password%20FROM%20users--\" \"python-requests/2.32.3\"\n2026-10-07T21:09:33+00:00 2001:db8:1::/48 monitor-reject 403 \"restricted\" rule=request-shield.rules:5 \"GET http://www.example.org/admin/index.php\" \"curl/8.5.0\"\n2026-10-07T21:09:34+00:00 192.0.2.0/24 monitor-challenge 429 \"requests\" rule=request-shield.rules:4 \"GET http://www.example.org/index.php?page=61\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36\"\n2026-10-07T21:09:34+00:00 203.0.113.0/24 monitor-reject 403 \"attack\" rule=ATK-XSS-TAG \"GET http://www.example.org/index.php?q=%3Cscript%3Ealert(1)%3C/script%3E\" \"curl/7.68.0\"",
        'installLogLegend' => 'Zeit · Adresse (anonymisiert auf ihr Netz) · was er getan hätte · Status · Grund · Regel (ihre ID, oder Datei:Zeile) · die Anfrage · der Browser. Jeder dieser Besucher bekam trotzdem seine Seite.',
        'liveLogTitle' => 'Das Log dieser Seite — live',
        'liveLogLead' => 'Was der Shield hier gerade abweist, prüft oder bremst, wie es in seiner Log-Datei steht (set log). Klick ein paar Karten an.',
        'liveLogEmpty' => 'Noch nichts im Log — schick oben eine Anfrage.',
        'liveLogWide' => 'Breiter / schmaler', 'liveLogNice' => 'Aufbereitet', 'liveLogRaw' => 'Original', 'liveLogMasked' => 'Adressen anonymisiert auf ihr Netz (log-ip masked)',
        'installMonitor' => 'Erst beobachten: Mit <code>set mode monitor</code> weist der Shield niemanden ab und schreibt ins Log (<code>set log</code>), was er getan hätte — in jeder dieser Zeilen steht <code>monitor-reject</code>, <code>monitor-throttle</code> … Ohne <code>set log</code> gibt es keine Log-Datei.',
        'footer' => 'request-shield · MIT-Lizenz · eine Demo, die auf deinem Rechner läuft',
        'notes' => [
            'every rule\'s name starts with SHOW-: decisions and the log name it' => 'jede Regel heißt SHOW-…: Entscheidungen und Log nennen den Namen',
            'this rule set\'s own version' => 'die Version dieser Regeln',
            'the proxy in front: from it, X-Forwarded-For names the visitor' => 'der Proxy davor: von ihm nennt X-Forwarded-For den Besucher',
            'The page sends each try as a visitor of its own (X-Forwarded-For from this' => 'Die Seite schickt jeden Versuch als eigenen Besucher (X-Forwarded-For von dieser',
            'machine), so a try never blocks you. A real site trusts its proxy here.' => 'Maschine) — so sperrt dich kein Versuch aus. Eine echte Website nennt hier ihren Proxy.',
            'Built in, without a line: scanners\' paths, path traversal, broken requests.' => 'Eingebaut, ohne eine Zeile: Pfade der Scanner, Path-Traversal, kaputte Anfragen.',
            'utm_*, fbclid, gclid: newsletter and ad links keep working' => 'utm_*, fbclid, gclid: Newsletter- und Werbelinks funktionieren weiter',
            'SQL injection, XSS, shell commands -- in the free text only' => 'SQL-Injection, XSS, Shell-Befehle — nur im freien Text',
            'the parameters the site knows, and their types' => 'die Parameter, die die Seite kennt, und ihre Typen',
            'any other parameter, or a wrong type: 404' => 'jeder andere Parameter oder ein falscher Typ: 404',
            'per visitor: 60 a minute pass silently, then the invisible check, past 120 a pause' => 'pro Besucher: 60 pro Minute laufen still durch, dann der unsichtbare Check, über 120 eine Pause',
            'forms may only be sent to the contact page and the sign-in' => 'Formulare dürfen nur an die Kontaktseite und den Login',
            'the search counts itself: 5 searches a minute per visitor' => 'die Suche zählt selbst mit: 5 Suchen pro Minute und Besucher',
            'past them a pause: 5 seconds, then 10, 20, 40 …' => 'danach eine Pause: 5 Sekunden, dann 10, 20, 40 …',
            'the sign-in counts wrong passwords: 3 in 15 minutes' => 'der Login zählt falsche Passwörter: 3 in 15 Minuten',
            'then a pause: 5 seconds, then 10, 20, 40 …' => 'dann eine Pause: 5 Sekunden, dann 10, 20, 40 …',
            'every pause twice as long as the one before' => 'jede Pause doppelt so lang wie die davor',
            'The API: a form sends JSON to it, other programs read products as JSON or XML.' => 'Die API: Ein Formular schickt ihr JSON, andere Programme lesen Produkte als JSON oder XML.',
            'a check there is JSON with a header, never a page a program cannot show' => 'ein Check ist dort JSON mit Header — nie eine Seite, die ein Programm nicht anzeigen kann',
            'a POST is let in here (and only where a rule allows it); PUT, DELETE … get 405 anyway' => 'ein POST ist hier erlaubt (und nur, wo eine Regel ihn erlaubt); PUT, DELETE … bekommen ohnehin 405',
            'its parameters, typed: anything else 404 (query strict)' => 'ihre Parameter, mit Typ: alles andere 404 (query strict)',
            'per visitor: 30 calls a minute, then 429 with Retry-After' => 'pro Besucher: 30 Aufrufe pro Minute, dann 429 mit Retry-After',
            'every write needs a pass: a browser solves the task unseen, a script pays per request' => 'jedes Schreiben braucht einen Pass: ein Browser löst die Aufgabe unsichtbar, ein Skript zahlt pro Anfrage',
            'but never longer than five minutes' => 'aber nie länger als fünf Minuten',
            '... and only from the site\'s own pages' => '… und nur von den eigenen Seiten',
            'the admin area: only the office network' => 'der Admin-Bereich: nur aus dem Büronetz',
            'the login: every visitor is checked (invisibly) first' => 'der Login: jeder Besucher wird zuerst (unsichtbar) geprüft',
            'an address kept out for good' => 'eine Adresse, die dauerhaft draußen bleibt',
            'verified AI training crawlers: no' => 'verifizierte KI-Trainings-Crawler: nein',
        ],
        'tries' => [
            'A visitor reads the front page' => 'Ein Besucher liest die Startseite',
            'A scanner looks for your passwords' => 'Ein Scanner sucht deine Passwörter',
            '... for your source code' => '… deinen Quellcode',
            '... for a database tool' => '… ein Datenbank-Werkzeug',
            '... for a forgotten backup' => '… ein vergessenes Backup',
            'SQL injection in the search' => 'SQL-Injection in der Suche',
            'A newsletter link: welcome' => 'Ein Newsletter-Link: willkommen',
            'A page number that is a number' => 'Eine Seitennummer, die eine Zahl ist',
            'A page "number" that is not one' => 'Eine „Seitennummer“, die keine ist',
            'A parameter the site does not know' => 'Ein Parameter, den die Seite nicht kennt',
            '61 pages in a minute: the invisible check' => '61 Seiten in einer Minute: der unsichtbare Check',
            '121 in a minute: a pause' => '121 in einer Minute: Pause',
            'A POST where no form is' => 'Ein POST, wo kein Formular ist',
            'The contact form, from the site' => 'Das Kontaktformular, von der eigenen Seite',
            'The contact form, sent from elsewhere' => 'Das Kontaktformular, von einer fremden Seite',
            'The admin area, from the office' => 'Der Admin-Bereich, aus dem Büro',
            'The admin area, from anywhere else' => 'Der Admin-Bereich, von woanders',
            'The login: checked first' => 'Der Login: erst der Check',
            '... with a pass: straight in' => '… mit Pass: direkt rein',
            'An address on the deny list' => 'Eine Adresse auf der Sperrliste',
            'The product list, as JSON' => 'Die Produktliste, als JSON',
            '... as XML' => '… als XML',
            'A parameter the API does not know' => 'Ein Parameter, den die API nicht kennt',
            '31 calls in a minute: a pause' => '31 Aufrufe in einer Minute: Pause',
            'A message without a pass: the check, as JSON' => 'Eine Nachricht ohne Pass: der Check, als JSON',
            '... from another website: post-origin does not apply to an API (programs send no Origin) -- the check does, and the browser\'s CORS' => '… von einer fremden Website: post-origin gilt für APIs nicht (Programme senden kein Origin) — der Check gilt, und das CORS des Browsers',
            'A message with a pass: it arrives' => 'Eine Nachricht mit Pass: kommt an',
            'A method the site does not take (built in: GET, HEAD, POST, OPTIONS)' => 'Eine Methode, die die Website nicht annimmt (eingebaut: GET, HEAD, POST, OPTIONS)',
            'The shield\'s own pages, from outside' => 'Die Seiten des Shields, von außen',
        ],
    ],
    'en' => [
        'title' => 'request-shield — bots out, people in',
        'nav' => ['what' => 'What it does', 'rules' => 'The rules', 'try' => 'Try it', 'exponential' => 'Exponential', 'install' => 'Install'],
        'heroEyebrow' => 'A friendly doorkeeper for PHP websites',
        'heroTitle' => 'Bots out.<br><span>People in.</span>',
        'heroLead' => 'request-shield lets your visitors in and politely sends scanners, spam and hasty bots on their way — before WordPress, Symfony or your CMS even wake up. No captcha, no cloud, one single file.',
        'mascot' => 'Hello! I look after your website.',
        'heroTry' => 'Try it live',
        'heroRules' => 'See how simple the rules are',
        'streamTitle' => 'What I decide right now — live',
        'stats' => [['~10 µs', 'per request'], ['0', 'dependencies'], ['1', 'file'], ['PHP 8.0+', 'runs anywhere']],
        'promiseTitle' => 'Protection that shuts nobody out',
        'promises' => [
            ['bi-universal-access-circle', 'Accessible', 'No picture puzzles, no audio captcha, no clicking traffic lights. The check runs by itself — nobody has to read, hear or operate anything, and a screen reader is told when it cannot go on. All it needs is JavaScript and cookies.'],
            ['bi-eye-slash', 'No tracking', 'No tracking cookie, no profile. Only a short, signed pass for security — tied to the address group and the browser, gone after an hour.'],
            ['bi-shield-lock', 'No third party', 'No Google, no Cloudflare, no CDN — the check runs on your server. Only the check of real crawlers asks a DNS resolver, and it can be switched off.'],
            ['bi-house-heart', 'On your own server', 'One PHP file, your rules, your logs. Runs on PHP 8.0 and nothing else — simple shared hosting included; with a writable folder in full, without one with the rules.'],
        ],
        'whatTitle' => 'What it does — without anyone noticing',
        'whatLead' => 'Most requests to a website do not come from people. request-shield sorts them out before they cost computing time.',
        'features' => [
            ['bi-bug', 'Scanners hit a wall', 'Whoever looks for .env, .git, phpMyAdmin or old backups gets a plain 404 — built in, without a line of configuration.'],
            ['bi-braces', 'Parameters with types', 'A page number is a number, a search is text. Anything else is a 404 — and attack patterns are looked for only where free text is.'],
            ['bi-speedometer2', 'Bots kept in step', 'Whoever clicks too fast gets an invisible browser check. People notice nothing, scripts pay in computing time.'],
            ['bi-envelope-check', 'Forms from your site only', 'Contact forms only take what your own pages send. Spam from other sites never arrives.'],
            ['bi-building-lock', 'Access by network', 'The admin area from the office only, the statistics from the server itself — one line per rule.'],
            ['bi-robot', 'Crawlers that prove who they are', 'Googlebot is Googlebot only from Google\'s addresses. AI training crawlers are kept out with one word.'],
        ],
        'rulesTitle' => 'The rules: as readable as a note on the door',
        'rulesLead' => 'This is this site\'s complete rule file — with values a real website uses. On the left the rule, on the right what it means.',
        'rulesNote' => 'In the file, every rule has an example below it (<code>expect</code>). <code>request-shield test</code> checks them all — the cards below are exactly these examples.',
        'tryTitle' => 'Try it',
        'tryLead' => 'Click your way through: every button sends a real request, and the shield answers at once. Don\'t worry — each card is a visitor of its own, you never lock yourself out.',
        'tryAll' => 'Send them all, one after another',
        'send' => 'Send',
        'sent' => 'Again',
        'expected' => 'expected',
        'from' => 'from',
        'simulated' => 'Decided on the server: no browser may forge another site\'s Origin — the server checks exactly this request with the real rules.',
        'passCard' => 'With a pass: open the login in a new tab. The invisible check runs for a second, then you are in.',
        'openLogin' => 'Open the login',
        'groups' => [
            'scan' => ['Scanners & attackers', 'Built in. Nothing to configure.'],
            'params' => ['Parameters with types', 'What the site does not know does not exist.'],
            'pace' => ['Bots kept in step', '60 pages a minute is a lot for a person — and little for a bot.'],
            'self' => ['Pages that count for themselves', 'The search and the sign-in count along. Whoever overdoes it waits — twice as long each time.'],
            'forms' => ['Forms', 'A POST only where a form is, and only from your pages.'],
            'api' => ['An API with JSON and XML', 'A form sends JSON to the API, other programs read products as JSON or XML. Its rules stand in a block of their own: match /api/** { … }'],
            'access' => ['Access', 'Who may go where — by address, with a check, or not at all.'],
        ],
        'burstTitle' => 'A bot sends 125 page views in a minute',
        'burstLead' => 'Up to 60: through. From 61: the invisible browser check (a person does not notice, a script has to compute). From 121: a pause.',
        'burstGo' => 'Send 125 requests',
        'burstLegend' => ['through', 'browser check', 'pause'],
        'burstLog' => 'Show the requests',
        'exp' => [
            'title' => 'Example: an Exponential website',
            'lead' => 'Exponential (the CMS with siteaccesses, URL aliases and an admin interface) gets what every CMS gets: scrapers counting through node numbers, scanners asking for settings/site.ini, bots posting everywhere and hammering the search. The kernel spends 20 to 150 ms of PHP and database on each — the shield answers first.',
            'how' => 'Three rule files in examples/exponential and one line in config.php:',
            'decided' => 'These examples are decided on the server with the real Exponential rules (the admin as /admin, switched on), exactly as request-shield test does — nothing counted. A second website cannot really be called from inside this page.',
            'checkAll' => 'Check them all', 'check' => 'Check', 'rules' => 'The rules', 'why' => 'Why each rule: docs/use-cases/exponential.md', 'summary' => '%d of %d as expected',
            'groups' => ['The site' => 'The site', 'System URLs in the frontend' => 'System URLs in the frontend', 'Forms' => 'Forms', 'Search' => 'Search',
                'Pace and bans' => 'Pace and bans', 'The shield itself' => 'The shield itself', 'Admin (/admin)' => 'Admin (/admin)'],
        ],
        'api' => [
            'formTitle' => 'A form that sends JSON to the API', 'formLead' => 'As on a modern website: the form sends JSON with fetch() to POST /api/v1/messages. The steps below are real.',
            'name' => 'Name', 'message' => 'Message', 'send' => 'Send', 'bot' => 'Send as a bot (no browser, a new address)', 'forget' => 'Forget the pass',
            'sent' => 'Sent: POST /api/v1/messages, Content-Type: application/json', 'challenge' => 'Answer 429: the API asks for the check — the task is JSON in the header Request-Shield-Challenge',
            'solved' => 'The browser solves the task unseen: %d ms', 'resend' => 'Sent again, the solution in the header Request-Shield-Solution',
            'done' => 'Answer %d: %s', 'pass' => 'The browser now holds a pass (a cookie, one hour): the next message goes straight through.',
            'botDone' => 'A script without a browser gets only this: 429 and a task it would have to compute anew for every message.', 'forgotten' => 'Pass forgotten — the next message asks for the check again.',
            'whyTitle' => 'Why these rules?',
            'why' => [
                ['api-path /api/**', 'A program cannot show a check page. On /api/** the shield therefore answers in JSON: the check as a task in a header, a refusal (404, 403, 429) as JSON with a reference.'],
                ['allow POST', 'The API takes GET and POST. PUT, DELETE and other methods are refused (405) before PHP even runs.'],
                ['query page int · limit int · format json|xml', 'Page and count are numbers, the format json or xml. Any other parameter or value: 404 — attack patterns find no room.'],
                ['limit api 30/min', 'Each visitor may call 30 times a minute. Then 429 with Retry-After: a scraper does not read the catalogue in seconds.'],
                ['challenge POST', 'Every write needs a pass. A browser solves the task unseen, once an hour; a spam script has to compute anew for every message.'],
                ['post-origin — not here', 'post-origin does not apply to an API, as programs send no Origin. Against other websites the browser protects here: JSON from another site needs a CORS preflight, which the API does not answer.'],
                ['The content', 'The shield does not read the JSON itself. The API checks type, fields and lengths (415, 422) — that stays its job.'],
            ],
        ],
        'self' => [
            'searchTitle' => 'A search that counts', 'searchLead' => '5 searches a minute for each visitor. Then a pause — 5 seconds, then 10, 20, 40 …',
            'searchPlaceholder' => 'Search term', 'searchGo' => 'Search', 'hits' => '%d results for "%s"',
            'loginTitle' => 'A sign-in that counts wrong passwords', 'loginLead' => '3 wrong passwords in 15 minutes go through, then a pause — 5 seconds, then 10, 20, 40 … A right password counts nothing.',
            'user' => 'User', 'password' => 'Password', 'pwHint' => 'The right password is "sesam".', 'loginGo' => 'Sign in',
            'wrong' => 'Wrong password.', 'welcome' => 'Welcome, demo!', 'pause' => 'A pause — the shield answers instead of the page. Possible again in %d s.', 'limit' => 'Limit spent — the shield answers for the page, and a pause begins.', 'legendLimit' => 'limit spent, a new pause',
            'botGo' => 'Bot mode: 60 seconds, one try a second', 'botStop' => 'Stop', 'newVisitor' => 'New visitor',
            'botSummary' => '%d of %d tries reached the page.', 'blockFor' => 'pause %d s', 'legendReached' => 'reached', 'legendRefused' => 'refused',
            'visitor' => 'Visitor: X-Forwarded-For %s',
        ],
        'burstFrom' => 'all from one visitor',
        'say' => ['answered' => 'Come in! The page is delivered.', 'check' => 'A quick, invisible check — people notice nothing.', '403' => 'Friendly but firm: no entry.',
            '404' => 'Nothing to find here.', '405' => 'That is not possible here.', '429' => 'A short pause, please.', '400' => 'That is no valid request.'],
        'details' => 'Details',
        'outcome' => ['passes' => 'let through', 'uncached' => 'through, not cached', 'answered' => 'let through', 'check' => 'browser check', '403' => 'refused', '404' => 'not found', '405' => 'not allowed', '429' => 'pause', '400' => 'broken request'],
        'checkTitle' => 'The browser check nobody sees',
        'checkSteps' => [
            ['bi-hourglass-split', 'The browser gets a small sum to work out', 'Signed, bound to its address, expired after a few minutes.'],
            ['bi-cpu', 'It solves it in a fraction of a second', 'A person briefly sees "One moment …". No picture, no click, no puzzle.'],
            ['bi-ticket-perforated', 'It gets a pass', 'A signed cookie. The next pages come straight through — for a bot, every new address costs computing time again.'],
        ],
        'checkTry' => 'See for yourself: open the login',
        'checkNote' => 'Accessible, no tracking, no third party — it runs on your own server.',
        'installTitle' => 'On your website in three steps',
        'install' => [
            ['Upload the file', 'Put request-shield.php and your rules in a folder of their own — outside the document root, so nobody can fetch them in a browser. Next to them the shield makes its folder .request-shield/ (counters, key); the folder must be writable.',
                "/home/example/\n├── request-shield/            ← new, outside the document root\n│   ├── request-shield.php     ← the one file\n│   └── request-shield.rules   ← your rules (step 3)\n└── public_html/               ← your website, as before"],
            ['Include it', 'Choose one way. auto_prepend_file (.htaccess or .user.ini) protects every PHP file of the website; require only what runs through that file.', ''],
            ['Write and check the rules', 'Start with a few lines and let the shield watch first. The command checks the rules and tells you what your hosting can do.',
                "# request-shield.rules — next to request-shield.php\ninclude @tracking                          # newsletter and ad links keep working\ninclude @attacks                           # SQL injection, XSS … in free text\nlimit requests 120/min challenge-at 60     # past 60 a minute: the invisible check\nrestrict /admin/** to 192.0.2.0/24         # the admin area: the office only\nset mode monitor                           # watch first; later: set mode enforce\nset log /home/example/request-shield/shield.log   # what it would have done goes here"],
        ],
        'installCheck' => "# in the folder request-shield/, over SSH\nphp request-shield.php check request-shield.rules\n\n# what it would have done, as it happens\ntail -f shield.log | grep monitor-",
        'installWays' => [
            ['.htaccess', "# .htaccess in the document root (public_html/) — Apache with mod_php, LiteSpeed\nphp_value auto_prepend_file /home/example/request-shield/request-shield.php",
                'Error 500 after saving? Then PHP runs as FPM — use .user.ini instead.'],
            ['.user.ini', "; .user.ini in the document root (public_html/) — PHP-FPM, LiteSpeed LSAPI\nauto_prepend_file = /home/example/request-shield/request-shield.php",
                'PHP reads .user.ini again only after a few minutes (user_ini.cache_ttl, usually 5 minutes).'],
            ['index.php', "<?php\n// at the very top of public_html/index.php — before anything else\nrequire '/home/example/request-shield/request-shield.php';\n\n// … your code from here, as before",
                'For sites with a front controller (Symfony, Laravel, Exponential). The shield finds the rules next to the file; another place is named by define(\'REQUEST_SHIELD_CONFIG\', \'…/my.rules\') before the require.'],
            ['WordPress', "<?php\n// at the very top of wp-config.php, right after <?php\nrequire '/home/example/request-shield/request-shield.php';\n\n// … define( 'DB_NAME', … ); as before",
                'Or by .htaccess / .user.ini: then every PHP file is protected too, also those WordPress does not load itself.'],
        ],
        'copy' => 'Copy', 'copied' => 'Copied',
        'installLogTitle' => 'This is the log in monitor mode — real, with exactly these rules:',
        'installLog' => "2026-10-07T21:09:33+00:00 198.51.100.0/24 monitor-reject 404 \"blocked path\" rule=SCAN-HIDDEN \"GET http://www.example.org/index.php/.env\" \"Mozilla/5.0 (compatible; Scanner/1.0)\"\n2026-10-07T21:09:33+00:00 203.0.113.0/24 monitor-reject 403 \"attack\" rule=ATK-SQL-UNION \"GET http://www.example.org/index.php?q=1%27%20UNION%20SELECT%20password%20FROM%20users--\" \"python-requests/2.32.3\"\n2026-10-07T21:09:33+00:00 2001:db8:1::/48 monitor-reject 403 \"restricted\" rule=request-shield.rules:5 \"GET http://www.example.org/admin/index.php\" \"curl/8.5.0\"\n2026-10-07T21:09:34+00:00 192.0.2.0/24 monitor-challenge 429 \"requests\" rule=request-shield.rules:4 \"GET http://www.example.org/index.php?page=61\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36\"\n2026-10-07T21:09:34+00:00 203.0.113.0/24 monitor-reject 403 \"attack\" rule=ATK-XSS-TAG \"GET http://www.example.org/index.php?q=%3Cscript%3Ealert(1)%3C/script%3E\" \"curl/7.68.0\"",
        'installLogLegend' => 'Time · address (masked to its network) · what it would have done · status · reason · rule (its ID, or file:line) · the request · the browser. Each of these visitors still got their page.',
        'liveLogTitle' => 'This page\'s log — live',
        'liveLogLead' => 'What the shield refuses, checks or slows down here right now, as its log file has it (set log). Click a few cards.',
        'liveLogEmpty' => 'Nothing in the log yet — send a request above.',
        'liveLogWide' => 'Wider / narrower', 'liveLogNice' => 'Readable', 'liveLogRaw' => 'Original', 'liveLogMasked' => 'Addresses masked to their network (log-ip masked)',
        'installMonitor' => 'Watch first: with <code>set mode monitor</code> the shield refuses nobody and writes to its log (<code>set log</code>) what it would have done — each of these lines says <code>monitor-reject</code>, <code>monitor-throttle</code> … Without <code>set log</code> there is no log file.',
        'footer' => 'request-shield · MIT licence · a demo running on your own machine',
        'notes' => [],
        'tries' => [],
    ],
];
